lib/src/auth_response.dart, lib/src/firebase.dart, test/test.dart
I added createUser(), removeUser() and authWithPassword().
As a consequence of that, I also needed to change AuthResponse.auth to type JsObject rather than String, although perhaps it should just be untyped.
Thoughts?
Also, if I execute async methods within a Dart test, there seems to be no way to wait for completion other than chaining async calls together using .then().  Which is what I do in the auth-credentials test group.  The test seems a bit monolithic, but if I write separate tests for createUser(), removeUser() and authWithPassword(), then there's a race toward failure.
How do you want to see these tests structured?  I would be happy to fix.
=> Add createUser(), removeUser() and authWithPassword()

test/test.dart
The proposed solution to #24 is to set the StreamController constructor's `sync` parameter to `true`, to ensure that events are passed directly to the streams' listeners thereby ensuring that listeners see events in the order that must be guaranteed per the Firebase specification.
=> Resolve #24 ("Events triggered out-of-order") and add test case.

test/test.dart
Very very small addition, I was going to try and implement the `authAnonymously` but this stopped me.
=> fix a bracket mismatch in test.dart

CHANGELOG.md, README.md, lib/src/data_snapshot.dart, lib/src/disconnect.dart, lib/src/firebase.dart, pubspec.yaml, test/test.dart, test/test.html
Updated to work with firebase api v. 2.2.2  
Several apis had changed to only send one parameter to a method's callback which will be either an Error, or null. Previously the JS apis returned the error as the first argument, and the result or null as the second.
createUser() will now return user data on success, not simply null.
'name' getter on Firebase is deprecated in favor of 'key'
Data Snapshot now has 'exists' getter (new in api version 2.0.4)
Added the changeEmail() method which became available with api version 2.1.0
Query object now has limitToFirst(), limitToLast(), equalTo(), orderByChild(), orderByKey(), orderByValue() and orderByPriority()
=> Updated to work with and add methods for Firebase api v2.2.2

lib/src/firebase.dart
This should be the very last method missing from the dart port. I skipped it initially because I wasn't sure how to verify it worked.  I took the time to figure it out today and that's when I realized how much data we aren't returning in the AuthResponse (issue #41)
=> added authWithOAuthToken() method.

lib/src/firebase.dart, test/test.dart
attempting to address issue #45 
Added several tests to ensure queries are behaving as expected. The parameters could either be named similar to how they were before or they could simply be positional like the javascript api. For now I kept named parameters because that is what the library authors originally went with. I did adjust the names to match the api: value & key
=> updated startAt() and endAt() to fix issue #45

CHANGELOG.md, lib/src/firebase.dart, pubspec.yaml, test/firebase_test.dart
I had to write a kind of awkward _ServerValue class to get the syntax to the be the same as the js side.
The test may be overly specific. It tests the value of `TIMESTAMP` and not just that it exists.
=> Define Firebase.ServerValue.TIMESTAMP

README.md
I think we should explicitly mention the pubspec dependency in readme. Because of the latest (not backward compatible) update.
=> Dependencies mention in readme

lib/src/app.dart, lib/src/auth.dart, lib/src/database.dart, lib/src/interop/database_interop.dart, lib/src/interop/storage_interop.dart, lib/src/js.dart, lib/src/storage.dart, lib/src/top_level.dart, lib/src/utils.dart, test/storage_test.dart
If a wrapper needs to be cached, let's let the wrapper handle it
Also allows JsObjectWrapper.jsObject to be final
=> Eliminate one-off caches in favor of expando

README.md
The [existing link](https://github.com/firebase/firebase-dart/tree/docs#using-this-package-with-the-dart-vm-and-fuchsia) led to a 404.
=> Fix README header anchor to Dart VM and Fuchsia

lib/src/utils.dart, test/utils_test.dart
There's a TODO in the code to find a better way to verify an object is a GeoPoint. AFAICT a geopoint will only ever have two keys: https://firebase.google.com/docs/reference/js/firebase.firestore.GeoPoint but this could be a wrong assumption.
=> check geopoint key length

CHANGELOG.md, README.md, lib/src/interop/storage_interop.dart, lib/src/storage.dart, test/storage_test.dart
Sorry for the mess!
Only important thing to note is that using the List API (and thus testing it) requires updating storage rules to version 2.
```
rules_version = '2';
service firebase.storage {
...
}
```
=> Support storage list API

lib/src/interop/messaging_interop.dart, lib/src/messaging.dart
According to Firebase docs -- firebase. messaging:
Functions
isSupported
isSupported(): boolean
Returns boolean
The function is accessed in js by firebase.messaging.isSupported(), here as a static member of the Messaging class (Messaging.isSupported()).
There are no tests for Messaging.
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
=> Feature: Messaging.isSupported()

CHANGELOG.md, lib/src/firestore.dart, lib/src/interop/firestore_interop.dart, test/firestore_test.dart
Executing queries on collection groups [requires](https://firebase.google.com/docs/firestore/security/rules-query#collection_group_queries_and_security_rules) rules version 2 and indexes with group queries specifically enabled. However, they're just normal queries as far as interop is concerned so I don't think  they need any additional test coverage. 
Closes #223
=> Support firestore collectionGroup

CHANGELOG.md, lib/src/auth.dart, lib/src/interop/auth_interop.dart
The email link sign in method provided by Firebase Auth is not yet implemented. Adding it, since I need it for my Flutter Web project.
=> Add email link sign in bindings

lib/src/interop/firestore_interop.dart
Added the missing options from [Settings](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings) to allow usage of [Emulator Suite](https://firebase.google.com/docs/emulator-suite)
=> Added firestore interop options to settings to work with Emulator Suite

README.md, pubspec.yaml
These links in the README were 404ing. If those projects have been deleted/discontinued we should remove them (this PR)
If they have moved/merged into different projects, let me know I can update the links instead of removing them.
=> docs: fix 404 links

CHANGELOG.md, lib/src/analytics.dart, lib/src/interop/analytics_interop.dart, pubspec.yaml
Fix for https://github.com/FirebaseExtended/firebase-dart/issues/309
Tested by checking the chrome debug console:
And the firebase analytics debug console:
Environment in which it was tested:
Dart version: 2.8.0
OS: windows
Flutter doctor just in case:
```
[√] Flutter (Channel dev, v1.16.1, on Microsoft Windows [Version 10.0.18363.752], locale en-US)
• Flutter version 1.16.1 at C:\dev\flutter
• Framework revision e6b0f5f238 (11 days ago), 2020-03-18 21:56:02 -0400
• Engine revision 216c420a2c
• Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:\dev\android_home
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2 …
```
=> Enabled sending of user properties

lib/src/app.dart, lib/src/remote_config.dart
Since Dart 2.1, Future and Stream have been exported from dart:core
=> Remove unused dart:async imports

CHANGELOG.md, lib/src/storage.dart, pubspec.yaml
This ensures the onCompletion function created to handle UploadTasks doesn't return anything.
All tests pass, I tried to write a test for this case, but I wasn't able to pick up the exception with something like this in `storage_test.dart`:
```dart
test('does not throw in another zone', () async {
final storage = app.storage();
final subfolder = storage.ref(validDatePath()).child('sub');
await runZonedGuarded(() async {
final task = subfolder.putString('testing 1 2 3');
task.pause();
// The error only gets thrown when we listen to the status updates
final subscription = task.onStateChanged.listen((event) => event);
subscription.onDone(() {
print('stream done!');
subscription.cancel();
});
await Future.delayed(const Duration(seconds: 10));
task.resume();
await expectLater(task.future, …
```
=> [storage] Ensure onCompletion for UploadTasks don't return anything.

CHANGELOG.md, lib/src/functions.dart, pubspec.yaml
Changing the data type of the cloud function return data from Map<String, dynamic> to dynamic, so that any type of data can be received as a cloud function return
=> Change data type for the data returned from function call

firebase/CHANGELOG.md, firebase/lib/src/analytics.dart, firebase/lib/src/interop/analytics_interop.dart
This PR aims to relax null safe type restrictions to allow `null` values where other platform implementations also allow `null` values.
See this comment for more details: https://github.com/FirebaseExtended/flutterfire/pull/5341#issuecomment-802318246
tl;dr: There are some types in this package that don't allow `null` values, but on other platforms explicitly allow `null` values.
These `null` values are often important as the `null` value signals that a property should be reset.
For example, setting a `null` `screenName` or `uid` resets it in all further analytics events.
Or setting a user property to `null` removes this user property for the user.
Blocks https://github.com/FirebaseExtended/flutterfire/pull/5341
/cc @kevmoo mentioning you here as you've did the null-safe PR :)
=> Relax analytics null safe restrictions
