FirebaseExtended/firebase-dart

- lib/src/firebase.dart
- test/test.dart
adding getAuth() method so you can check at any time if a user is authenticated or not.
> adding getAuth() method

- lib/src/firebase.dart
Added onAuth listener so you can be notified of changes in a user's authentication status immediately:  https://www.firebase.com/docs/web/api/firebase/onauth.html
Usage: 
void authListener(authData) {
if(authData != null) {
// do something
}
}
fb.onAuth().listen(authListener);
> added onAuth listener

- lib/src/firebase.dart
- test/test.dart
added authAnonymously to create a temporary guest user:  https://www.firebase.com/docs/web/guide/login/anonymous.html
> added authAnonymously method

- lib/src/firebase.dart
Here is a clean pull request with only the appropriate methods. I accidentally jacked up the branch on #30
> added authWithOAuthPopup() and authWithOAuthRedirect()

- CHANGELOG.md
- lib/src/auth_response.dart
- lib/src/firebase.dart
- pubspec.yaml
- test/test.dart
> Updating auth data

- pubspec.yaml
- test/firebase_test.dart
Issues with transactions when compiled to JS
> skip one transaction test due to #52

- .travis.yml
- tool/travis.sh
Waiting on https://github.com/firebase/firebase-dart/pull/53
> Add travis continuous integration

- CHANGELOG.md
- lib/firebase.dart
- lib/firebase_io.dart
- lib/src/consts.dart
- lib/src/encode.dart
- test/encode_test.dart
- test/firebase_io_test.dart
- test/firebase_test.dart
- test/test_shared.dart
@sethladd thanks for helping with these.
> More io features

- lib/firebase_io.dart
- test/firebase_io_test.dart
Adds POST from the Firebase REST API to firebase_io. As one, focused commit. ;)
Includes tests.
> Add POST support from Firebase REST API

- lib/firebase_io.dart
> Fix FirebaseClient.post() so it calls POST

- lib/src/disconnect.dart
- lib/src/firebase.dart
- test/firebase_test.html
> add unused parameter to accept null parameter in onComplete callbacks

- AUTHORS
- CONTRIBUTING.md
- lib/src/assets/assets.dart
- pubspec.yaml
- test/database_test.dart
- test/io_test.dart
> Prep for release

- README.md
- example/auth/index.html
- example/realtime_database/index.html
- example/storage/index.html
- test/app_test.html
- test/auth_test.html
- test/database_test.html
- test/storage_test.html
They fixed some timing issues, maybe there will no longer be the problem with the auth test :-)
> Update to the latest version

- CHANGELOG.md
- README.md
- example/auth/index.html
- example/realtime_database/index.html
- example/storage/index.html
- pubspec.yaml
- test/app_test.html
- test/auth_test.html
- test/database_test.html
- test/storage_test.html
- tool/travis.sh
Updated the version of the JS API referenced in the readme and tests
Updated version and changelog
Tweak to output in tool/travis.sh
> Prepare for 3.0.1

- CHANGELOG.md
- lib/firebase_io.dart
- pubspec.yaml
> Throw `FirebaseClientException` if there are request failures

- CHANGELOG.md
- lib/src/auth.dart
- lib/src/interop/auth_interop.dart
- pubspec.yaml
- test/auth_test.dart
> Providers addScope and setCustomParameters fix

- .travis.yml
- CHANGELOG.md
- pubspec.yaml
- tool/travis_before_script.sh
> Use latest Travis-CI dart tasks

- CHANGELOG.md
- README.md
- example/auth/index.html
- example/realtime_database/index.html
- example/storage/index.html
- lib/src/app.dart
- lib/src/auth.dart
- lib/src/interop/app_interop.dart
- lib/src/interop/auth_interop.dart
- lib/src/interop/firebase_interop.dart
- pubspec.yaml
- test/app_test.dart
- test/app_test.html
- test/auth_test.dart
- test/auth_test.html
- test/database_test.html
- test/storage_test.html
Changes: https://firebase.google.com/support/release-notes/js#3.8.0
> New release

- CHANGELOG.md
- lib/src/auth.dart
- lib/src/database.dart
- lib/src/interop/database_interop.dart
- pubspec.yaml
- test/database_test.dart
> Added toJson to DataSnapshot and Query

- example/auth/index.dart
- lib/src/interop/js_interop.dart
- lib/src/utils.dart
And added a feature to the auth example
> Simplify dart-js object swapping

- CHANGELOG.md
- README.md
- example/auth/index.dart
- example/auth/index.html
- example/auth_phone/index.html
- example/realtime_database/index.html
- example/storage/index.html
- lib/src/auth.dart
- lib/src/interop/auth_interop.dart
- lib/src/interop/firebase_interop.dart
- lib/src/interop/storage_interop.dart
- lib/src/storage.dart
- pubspec.yaml
- test/app_test.html
- test/auth_test.dart
- test/auth_test.html
- test/database_test.html
- test/storage_test.html
> New release 4 3 1

- CHANGELOG.md
- analysis_options.yaml
CC @Janamou 
- Good keep line lengths at 80 chars – even for the changelog.
> Small tweaks

- example/auth/index.dart
- example/auth/index.html
@kevmoo Here is update with lang selection for verify email: #127
> Example lang

- README.md
> Make it clear when you should use this library

- example/firestore/index.dart
- lib/src/firestore.dart
- lib/src/interop/js_interop.dart
- lib/src/utils.dart
- test/firestore_test.dart
Fixes https://github.com/firebase/firebase-dart/issues/138
> support timestamp/DateTime

- CHANGELOG.md
- lib/src/interop/js_interop.dart
- lib/src/utils.dart
- pubspec.yaml
- test/firestore_test.dart
> Special type handling

- lib/src/interop/firestore_interop.dart
- lib/src/utils.dart
- test/firestore_test.dart
Also made GeoPoint fields read-only, per Firestore Documentation
> Support GeoPoint as a Document value

- CHANGELOG.md
- README.md
- example/auth/index.html
- example/auth_phone/index.html
- example/firestore/index.html
- example/realtime_database/index.html
- example/storage/index.html
- lib/src/firestore.dart
- lib/src/interop/firestore_interop.dart
- lib/src/utils.dart
- pubspec.yaml
- test/app_test.html
- test/auth_test.html
- test/database_test.html
- test/firestore_test.dart
- test/firestore_test.html
- test/storage_test.html
> Update to 4.9.1

- .gitignore
> And .dart_tool to .gitignore – and other cleanup

- CHANGELOG.md
- lib/firestore.dart
- lib/src/firestore.dart
- lib/src/interop/firestore_interop.dart
- lib/src/utils.dart
- test/firestore_test.dart
FieldValue is now a dart type as there is no way to call FieldValue.arrayUnion(var_args) js method directly. Source compatibility is preserved. Add unit test.
> feat: add support for FieldValue.arrayUnion and FieldValue.arrayRemove

- CHANGELOG.md
- lib/firebase.dart
- lib/src/analytics.dart
- lib/src/interop/analytics_interop.dart
- lib/src/interop/firebase_interop.dart
- lib/src/interop/performance_interop.dart
- lib/src/performance.dart
- lib/src/top_level.dart
- pubspec.yaml
I wanted to use firebase analytics in my flutter web project so I added it here
Note: I only implemented the functions I used
I'm new to this, so I would love to get feedback about my code (especially if I did something wrong)
Thanks :)
> Firebase Analytics & Performance Interop

- CHANGELOG.md
- lib/src/auth.dart
- lib/src/interop/auth_interop.dart
- test/auth_test.dart
Fixes https://github.com/FirebaseExtended/firebase-dart/issues/272
> Add Auth.fetchSignInMethodsForEmail

- CHANGELOG.md
- lib/src/auth.dart
- lib/src/interop/auth_interop.dart
- test/auth_test.dart
Fixes https://github.com/FirebaseExtended/firebase-dart/issues/273
> Add isSignInWithEmailLink

- pubspec.yaml
> Remove analyzer hack

- CHANGELOG.md
- lib/src/interop/firestore_interop.dart
- pubspec.yaml
Fixes Issues with Timestamps returned by Firestore
Fixes isssue #306
> Added Additional Option to Firestore Settings to fix #306

- firebase/lib/src/functions.dart
As of Dart 2.1, Future/Stream have been exported from dart:core.
> Remove unused dart:async imports.

- firebase/CHANGELOG.md
- firebase/lib/src/storage.dart
- firebase/pubspec.yaml
Eliminate throw during UploadTask.onStateChanged event.
Closes https://github.com/FirebaseExtended/firebase-dart/pull/351
> [firebase_storage] Fixed accessing timeCreated & updated variables

- firebase/CHANGELOG.md
- firebase/lib/firebase_io.dart
- firebase/pubspec.yaml
...from `BaseClient` to `Client` from `package:http`.
> Changed the type of `client` in the `FirebaseClient constructors

- firebase/CHANGELOG.md
- firebase/lib/src/firestore.dart
- firebase/lib/src/interop/firestore_interop.dart
Fixes https://github.com/FirebaseExtended/firebase-dart/issues/305
> Add support for PersistenceSettings

- firebase/CHANGELOG.md
- firebase/lib/src/auth.dart
- firebase/test/auth_test.dart
Fixes https://github.com/FirebaseExtended/firebase-dart/issues/265
> Add FutureOr<User> get currentUserAsync to Auth

- .github/workflows/dart.yml
- _shared_assets/pubspec.yaml
- firebase/CHANGELOG.md
- firebase/lib/src/top_level.dart
- firebase/mono_pkg.yaml
- firebase/pubspec.yaml
- tool/ci.sh
Removed unneeded import
Test on oldest stable supported SDK
Use latest mono_repo
Support latest dependencies
> A bunch of cleanup
